Fix Linking Book cover function
H-uru/Plasma pull request #1339
Opened 2023-02-26 22:55 UTC by DoobesURU

Adjust script to actually use cover image defined in `xLinkingBookDefs.py`. Fixes #1338 

The script currently makes the Relto shelf and some other Books gain the "default" cover and/or extra pages, so it's a draft for now.

2023-02-27 23:44 UTC, Hazado requested changes
``

2023-02-27 23:44 UTC, Hazado commented on Scripts/Python/xLinkingBookGUIPopup.py
> +                    showOpen = 0
```suggestion
                if showOpen and self.IsThereACover(bookdef):
                    showOpen = 0
```

2023-02-27 23:44 UTC, Hazado commented on Scripts/Python/xLinkingBookGUIPopup.py
> +                    showOpen = 0
Also Line 867 ` if idx > 0:` should be ` if idx >= 0:`
Anything other than -1 is true for string find

2024-11-10 00:57 UTC, Hoikas reviewed
A very belated review.....

2024-11-10 00:57 UTC, Hoikas commented on Scripts/Python/xLinkingBookGUIPopup.py
> +                    showOpen = 0
This doesn't feel right to me.... Whether or not a book should start open is hardwired to the following "logic":

```python
        if len(actBookshelf.value) == 0:
            agePanel = TargetAge.value
            showOpen = 1  # start pedestal books open
        else:
            agePanel = stringAgeRequested
            showOpen = 0    # start bookself books closed
  ```

Cyan seems to think anything we just find on a pedestal out in the world is "open" by definiton, but anything on a shelf is closed. That means these lines I'm commenting on *should* just be a safety valve for not showing a cover that doesn't exist, which would make this:

```suggestion
                if showOpen and not self.IsThereACover(bookdef):
                    showOpen = 0
```

2024-11-15 00:48 UTC, merged