fix Win7/8 resolution
H-uru/Plasma pull request #1580
Opened 2024-04-07 20:45 UTC by Filtik

In Windows 7 and Windows 8 the intro is very small and no mouse cursor is visible.
This fixes the problem.

2024-04-07 20:50 UTC, dpogue reviewed
This change does appear to be correct. After fetching the DPI value, we do `MulDiv(metricValue, dpiValue, 96)`, so I think the current (buggy) behaviour is dividing by 96 twice in some cases.

2024-04-07 21:01 UTC, Hoikas requested changes

2024-04-07 21:01 UTC, Hoikas commented on Sources/Plasma/PubUtilLib/plWinDpi/plWinDpi.cpp
> +            return UINT(float(dpiY));
```suggestion
            return dpiY;
```

2024-04-07 21:01 UTC, Hoikas commented on Sources/Plasma/PubUtilLib/plWinDpi/plWinDpi.cpp
> +    return UINT(float(ydpi));
```suggestion
    return UINT(ydpi);
```

2024-04-08 23:22 UTC, Hoikas approved these changes

2024-04-18 22:39 UTC, Hoikas commented
When you have a chance, please rebase this onto master so that we can get a proper CI run.

2024-05-02 02:21 UTC, merged