Fix issues with resource.dat generation on Windows.
H-uru/Plasma pull request #740
Opened 2020-12-13 01:31 UTC by Hoikas

This fixes our cairosvg dependency such that `pip install -r requirements.txt` works without undocumented dependencies. Further, some invalid assumptions have been corrected in makeres.py. Namely that: the python executable is named exactly `python` and that `pngcrush` is available when building an external client. This should also fix an issue where CMake would error if `CMAKE_RUNTIME_OUTPUT_DIRECTORY` is a generator expression.

2020-12-13 04:58 UTC, dpogue approved these changes
Looks good to me

2020-12-17 20:15 UTC, Deledrius requested changes
Works here for me.  Just one minor edit seems necessary.

2020-12-17 20:15 UTC, Deledrius commented on Sources/Plasma/Apps/plClient/external/makeres.py
> +		ret = subprocess.call([sys.executable, os.path.join(inpath, "render_svg.py"), "-i", inpath, "-o", os.path.join(workpath, "render")], stdout=sys.stdout, stderr=sys.stderr)
We should probably use `sys.executable` for the subprocess call to `create_resource_dat.py` as well.

2020-12-17 20:42 UTC, Deledrius approved these changes

2020-12-17 23:35 UTC, merged