MOULa December 2020 Update
H-uru/Plasma pull request #764
Opened 2020-12-26 01:52 UTC by DoobesURU

Updates .age and .fni files for GoMePubNew, VeeTsah, and ChisoPreniv. Note that these are the sequence prefixes for MOULa and Minkata.

Changelog: https://www.dropbox.com/s/o9d3d0taa1nzq07/MOUL%20changelog%20Dec2020.txt?dl=0

2020-12-27 01:13 UTC, Hoikas reviewed
Looks like the age and funny files are encrypted. Were there any SDL changes?

2020-12-27 11:44 UTC, DoobesURU commented
For the Pub, yes (the holiday deco book states). The Pub and Chiso also added new PRPs.

2020-12-27 19:58 UTC, Hoikas requested changes

2020-12-27 19:58 UTC, Hoikas commented on Scripts/SDL/GoMePubNew.sdl
> + @@ -1,45 +1,3 @@
```suggestion
```

2020-12-27 19:58 UTC, Hoikas commented on Scripts/SDL/GoMePubNew.sdl
> +
```suggestion
```

2021-01-08 18:20 UTC, Hoikas requested changes
The deletions need to be a new SDL version, of course :wink:

2021-01-08 18:20 UTC, Hoikas commented on Scripts/SDL/GoMePubNew.sdl
> +
There's still a some whitespace here ;)

2021-01-08 18:20 UTC, Hoikas commented on Scripts/SDL/GoMePubNew.sdl
> +    VAR BOOL    XMasVis[1]                       DEFAULT=0    DEFAULTOPTION=VAULT # Depreciated
```suggestion
```

2021-01-08 18:20 UTC, Hoikas commented on Scripts/SDL/GoMePubNew.sdl
> +    VAR BOOL    gmpnTikiDecoVis[1]               DEFAULT=0    DEFAULTOPTION=VAULT
```suggestion
```

2021-01-10 01:04 UTC, Hoikas approved these changes

2021-02-07 00:50 UTC, Hoikas commented
Merge concurrently with H-uru/moul-assets#14.

2021-02-18 19:20 UTC, merged