Fix Shroomie Gate state consistency
H-uru/Plasma pull request #793
Opened 2021-01-27 04:11 UTC by dpogue

The state was being modified regardless of whether the gate had power or not, but should only be changed when power is on (and when the relevant responders are run).

Closes #792.

2021-01-27 04:13 UTC, Deledrius approved these changes

2021-01-27 07:14 UTC, Hoikas requested changes
This only fixes half of the issue in that it prevents the state from changing when the power is off. The shroomie gate needs to respond (read: animate) when its state is changed.

2021-01-27 07:30 UTC, dpogue commented
My understand from the bug report is that it **does** animate properly when the power is on.

When the power is off, it (correctly) does not animate, but it did (incorrectly) change the state.

2021-01-27 07:33 UTC, Hoikas commented
My complaint is with something you will not observe in normal gameplay. That is, if you manually toggle the SDL variable `tldnShroomieGateUp`, then the visual state and the logical state will become desynchronized because the animation is triggered by the lever pull responder, not the actual state change. This will become a visual desynchronization if anyone links in after this operation.

2021-01-27 09:47 UTC, EhrenCG commented
Hey, I remembered my password!  I find GitHub a little complex and intimidating so thank you for submitting this!

Hoikas, I think I understand what you're talking about since you mentioned the scenario of what if someone changed the SDL in the background without physically pulling the lever?  Isn't this the sort of thing that needs an "OnSDLNotify" to make sure people would see it animate?

I guess this counts as a case of *ahem*... "appreciating" Cyan's programming.

2021-01-27 09:53 UTC, Hoikas commented
That's correct, @EhrenCG. Ideally, we want all of the game scripts to respond to SDL updates a) in case someone changes the SDL state and b) to ensure proper synchronization. Those kinds of changes might come from someone who is a shard admin using admin tools, someone playing around with an internal client, or a bot. As the fix currently stands, those actors would not be able to raise/lower the gate without requiring people link out and back into the Age, as you described in your bug report.

2021-01-28 00:02 UTC, EhrenCG commented
@Hoikas How widespread is this problem?  I just happened to look into GiraDoor.py.  It also has the same synch issue.  It even has OnSDLNotify commented out.  (Also, the info under the license refers to GiraDoor.py as "Module: Garden.py", heh.) I'm far from an expert in this stuff but it seems like a mess to me.  So maybe a lot of files have this issue, would take awhile to go through them all...

2021-01-28 04:30 UTC, dpogue commented
@Hoikas updated to use `OnSDLNotify`

2021-01-28 08:29 UTC, Hoikas reviewed
This could be cleaned up even more with `@property` accessors and mutators for the AgeSDL, but I won't insist on it.

2021-01-28 08:29 UTC, Hoikas commented on Scripts/Python/tldnShroomieGate.py
> +            respGateDown.run(self.key,fastforward=1)
```suggestion
            respGateDown.run(self.key, fastforward=True)
```

2021-01-28 08:29 UTC, Hoikas commented on Scripts/Python/tldnShroomieGate.py
> +            PtDebugPrint("tldnShroomieGate:\t---Shroomie Gate Up SDL: %d" % (ageSDL[kGateVariable][0]))
```suggestion
            PtDebugPrint(f"tldnShroomieGate:\t---Shroomie Gate Up SDL: {ageSDL[kGateVariable][0]}")
```

2021-01-28 08:29 UTC, Hoikas commented on Scripts/Python/tldnShroomieGate.py
> +            ff = True
```suggestion
        avatarKey = PtGetAvatarKeyFromClientID(playerID)
        avatar = avatarKey.getSceneObject() if avatarKey else None
        ff = avatar is None
```

2021-01-28 08:30 UTC, Hoikas commented
@EhrenCG Yep, looks like that one has the same issue. It's less noticeable, I expect, because it works fine under normal gameplay.

2021-01-28 17:19 UTC, Hoikas approved these changes

2021-01-28 18:03 UTC, merged